### ISSUE TITLE
大佬，部署阶段-编译成js静态页面访问不了或者登录后路由不转跳

### ISSUE THREAD

**Issue by InfernalAzazel** [tolking/element-admin-template#29]
我把编译的 dict 放到后端里面，之前用 antdv 写的没问题，是不是这个项目没有使用 vuex 状态导致？？？？静态页面不能访问.

不用编译的正常使用

err

```
index.cf2468a6.js:65 TypeError: i.then is not a function
    at index.cf2468a6.js:65:13807
    at index.cf2468a6.js:65:22467
B @ index.cf2468a6.js:65
（匿名） @ index.cf2468a6.js:65
Promise.catch（异步）
$ @ index.cf2468a6.js:65
$ @ index.cf2468a6.js:65
（匿名） @ index.cf2468a6.js:65
Promise.then（异步）
$ @ index.cf2468a6.js:65
w @ index.cf2468a6.js:65
（匿名） @ login.3a998de8.js:1
await in （匿名）（异步）
Il @ index.cf2468a6.js:4
ko @ index.cf2468a6.js:4
nk @ index.cf2468a6.js:4
（匿名） @ index.cf2468a6.js:65
Promise.then（异步）
d @ index.cf2468a6.js:65
Il @ index.cf2468a6.js:4
ko @ index.cf2468a6.js:4
nk @ index.cf2468a6.js:4
b @ index.cf2468a6.js:61
Il @ index.cf2468a6.js:4
ko @ index.cf2468a6.js:4
n @ index.cf2468a6.js:4
index.cf2468a6.js:4 TypeError: i.then is not a function
    at index.cf2468a6.js:65:13807
    at index.cf2468a6.js:65:22467
```

**Comment by InfernalAzazel** [comment]
固定路由没问题，异步动态路由就有问题了

**Comment by tolking** [comment]
如果是业务相关的问题可以根据错误提示自己处理，如果是提供的异步路由demo的问题，请指明

**Comment by InfernalAzazel** [comment]
code 和作者差不多的，编译后路由就有问题，调试没有任何问题 只有编译后使用dist 才会报错
```
import {createRouter, createWebHashHistory, createWebHistory, RouteRecordRaw} from 'vue-router'
import { NP } from "./np"
import {AllowList} from "./utils";
import {useGet, useGlobalState} from "./composables";
import {Api} from "./utils";
import {defineAsyncComponent} from "vue";
import {Router} from "./types";



const routes: RouteRecordRaw[] = [
    {
        path: '/login',
        meta:{hidden: true},
        component: () => import('./layout/login.vue'),

    },
    {
        path: '/init',
        meta:{hidden: true},
        component: () => import('./layout/init.vue'),

    },
]

const router = createRouter({
    history: createWebHashHistory(),
    routes,
})

const np = NP.init()
// 防止首次或者刷新界面路由失效
let initRoute = false
// const {data: routesData, execute: exeUsersRoutes} = useGet<Router[]>(Api.usersRoutes)

// 路由守卫
router.beforeEach(async (to, form, next) => {
    const state = useGlobalState()
    const {data: routesData, execute: exeUsersRoutes} = useGet<Router[]>(Api.usersRoutes)
    np.start()
    if (!AllowList.includes(to.path) && !state.value.access_token) {
        next(`/login?redirect=${to.path}`)
    } else if (to.path === '/login' && state.value.access_token) {
        next('/')
    } else if (!initRoute && to.path !== '/login' && state.value.access_token) {

        await exeUsersRoutes()
        // 获取路由 -> 转化 -> addRoute
        if (routesData.value){
            generateRoutes(routesData.value).forEach((item) => {
                router.addRoute(item)
                //@ts-ignore
                    ;(router.options.routes as RouteRecordRaw[]).push(item)
            })
        }
        initRoute = true
        next({ ...to, replace: true })
    } else {
        next()
    }
    np.done()
})

/**
 * 转化路由 NOTE: 根据需要修改
 * @param list 需要转化的路由
 */
function generateRoutes(list: Router[]): RouteRecordRaw[] {
    const state = useGlobalState()
    return list.reduce((all, item) => {
        // NOTE: 这里可以进行一些权限筛选，排除没有权限的路由
        // if (item.roles?.length && item.roles.includes('admin')) return all

        const children = item.children?.length
            ? generateRoutes(item.children)
            : undefined

        const current: RouteRecordRaw = {
            path: item.path,
            redirect: item.redirect,
            name: item.name,
            component: () => import(`./${item.component}`),
            children,
            meta: {
                title: state.value.locales === 'en-us' ? item.title_en_us: item.title_zh_cn ,
                icon: item.icon,
                hide: item.hide,
            },
        }

        return [...all, current]
    }, [] as RouteRecordRaw[])
}
export default router
```
具体报错信息

```
Failed to load resource: the server responded with a status of 404 (Not Found)
login.33068ee2.js:1 true
:3000/assets/layout/base.vue:1          Failed to load resource: the server responded with a status of 404 (Not Found)
index.d4b79f2d.js:65 TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:3000/assets/layout/base.vue
B @ index.d4b79f2d.js:65
index.d4b79f2d.js:4 TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:3000/assets/layout/base.vue
X9 @ index.d4b79f2d.js:4
:3000/assets/views/home/index.vue:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/#/login?redirect=/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:3000/assets/views/home/index.vue
```

**Comment by InfernalAzazel** [comment]
> 如果是业务相关的问题可以根据错误提示自己处理，如果是提供的异步路由demo的问题，请指明

完整的可以看我主页第一个仓库

**Comment by InfernalAzazel** [comment]
这是编译后的文件

![Screenshot from 2022-08-19 11-00-18](https://user-images.githubusercontent.com/40333954/185533593-b66d3323-736b-49f6-a166-99343965b73d.png)

**Comment by InfernalAzazel** [comment]
找到原因 vite2.0 编译机制不会对动态变量引用文件做处理，而 import.meta.glob 编译时会被标记，做编译处理,
所以大佬你的动态路由需要改一下

官方文档: https://cn.vitejs.dev/guide/features.html#glob-import

正确解法关键两条代码:

1. const modules = import.meta.glob('./**.vue');
2. modules[`./${item.component}`]
```
/**
 * 转化路由 NOTE: 根据需要修改
 * @param list 需要转化的路由
 */
function generateRoutes(list: Router[]): RouteRecordRaw[] {
    const state = useGlobalState()
    return list.reduce((all, item) => {
        // NOTE: 这里可以进行一些权限筛选，排除没有权限的路由
        // if (item.roles?.length && item.roles.includes('admin')) return all

        const children = item.children?.length
            ? generateRoutes(item.children)
            : undefined


        const modules = import.meta.glob('./**.vue');
        const current: RouteRecordRaw = {
            path: item.path,
            redirect: item.redirect,
            name: item.name,
            component: modules[`./${item.component}`],
            children,
            meta: {
                title: state.value.locales === 'en-us' ? item.title_en_us: item.title_zh_cn ,
                icon: item.icon,
                hide: item.hide,
            },
        }

        return [...all, current]
    }, [] as RouteRecordRaw[])
}
```
